---

spring:
  output:
    ansi:
      enabled:      always
  main:
    banner-mode:    log

logging:
  file:             './logs/baymax.log'
  file.max-history: 30
  file.max-size:    1GB

  level:
    root:           INFO
    space.npstr:    TRACE

sentry:
  dsn:              ""

baymax:
  discord-token:    ""
  status-type:      0          # 0 = "playing", 1 = "streaming", 2 = "listening"
  status-message:   "a game"
  staff-role-ids:
    - 479601466110377984
    - 242377373947920384
  help-desks:
  - channel-id:     487005342014636032
    model-name:     aki
    model-uri:      https://raw.githubusercontent.com/napstr/Baymax/master/models/aki.yaml
