services:

  bot:
    image: napstr/baymax:master
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - 127.0.0.1:5007:5005   # Remote debug
    volumes:
      - "./baymax-secrets.yaml:/opt/baymax/baymax-secrets.yaml:ro"
      - "./models:/opt/baymax/models:ro"
      - "./logs:/opt/baymax/logs"
      - "./logs/gc:/opt/baymax/logs/gc"
      - "./baymax.sqlite:/opt/baymax/baymax.sqlite"
    entrypoint:
      - java
      - -Xms512m
      - -Xmx512m
      - -XX:+AlwaysPreTouch
      - -XX:+HeapDumpOnOutOfMemoryError
      - -XX:HeapDumpPath=emergencydump.hprof
      - -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - -Xlog:gc*:logs/gc/gc-%t.log::filesize=1g
      #- -XX:+UseG1GC
      #- -XX:+ParallelRefProcEnabled
      - -XX:+UseZGC
      - -XX:+ZGenerational
      - -XX:+UseTransparentHugePages
      - -XX:+UseStringDeduplication
      - -jar
      - baymax.jar

  #watchtower:
  #  image: containrrr/watchtower
  #  restart: always
  #  labels:
  #    - "com.centurylinklabs.watchtower.enable=true"
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  #  command: --cleanup --label-enable --interval 300 #seconds
