version: '3.6'
services:

  bot:
    image: napstr/baymax:master
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - 127.0.0.1:5005:5005   # Remote debug
#      - 127.0.0.1:8849:8849   # JProfiler
    volumes:
      - "./baymax-secrets.yaml:/opt/baymax/baymax-secrets.yaml:ro"
      - "./models:/opt/baymax/models:ro"
      - "./logs:/opt/baymax/logs"
      - "./logs/gc:/opt/baymax/logs/gc"
      - "./baymax.sqlite:/opt/baymax/baymax.sqlite"
#    stop_grace_period: 60s
    entrypoint:
      - java
# Common JVM Options:
      - -Xms512m
      - -Xmx512m
      - -XX:HeapDumpPath=emergencydump.hprof
      - -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
# Hotspot Options:
      - -XX:+HeapDumpOnOutOfMemoryError
      - -Xlog:gc*:logs/gc/gc-%t.log::filesize=1g
      - -XX:+UseG1GC
      - -XX:+ParallelRefProcEnabled
      - -XX:+UseStringDeduplication
# Open J9 Options:
      #- -XX:+HeapDumpOnOutOfMemory
      #- -Xgcpolicy:balanced
      #- -Xverbosegclog:logs/gc/gc-%Y-%m-%d_%H-%M-%S.xml
# The Jar
      - -jar
      - baymax.jar

  #watchtower:
  #  image: v2tec/watchtower
  #  restart: always
  #  labels:
  #    - "com.centurylinklabs.watchtower.enable=true"
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  #  command: --cleanup --label-enable --interval 300 #seconds
